#!/usr/bin/env bash
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\suser ./user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (
:
:
:::)?80) /\180 /' /etc/nginx/sites-enabled/default
killall apache2
su nginx -c "systemctl restart nginx"
